### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-kubernetes-microprofile-config#1]
**What you'll learn**
- [x] The `Configuring microservices` guide ...
- [x] "It may not be immediately clear why this is beneficial to you when developing your micro services" You do not explain why it is beneficial right after so I'm not sure why you included this line here. 

**Deploy the name and ping applications**
- [x] `start` directory
- [x] Missing prerequisites
- [x] Include a line that states that the user should have docker running and Kubernetes enabled (if using docker) / corresponding minikube instructions
- [ ] It would be easier to have the two links clickable instead of http://[hostname].. etc and telling the user to put in the correct hostname depending on their environment.

**Create ConfigMap and Secret**
- [x] environment variable (typo in the word environment)
- [x] "Under the yaml for the containers" - do you mean the Kubernetes.yaml file? This was unclear to me

**Comment by proubatsis** [comment]
Since we're assuming some knowledge of Kubernetes and that they already have an environment setup, do we need a pre-requesites section? Maybe just a mention somewhere in the intro that `this guide assumes that you have a access to a Kubernetes cluster` or something alone those lines?

Any thoughts @gkwan-ibm @yeekangc ?

**Comment by justineechen** [comment]
I think you should state that they need to have their docker running and Kubernetes enabled before they run mvn package and at least have a link to the pre-requisites.

**Comment by proubatsis** [comment]
So, we should create a shared pre-reqs section in https://github.com/OpenLiberty/guides-common? 

The Kubernetes intro may require more detail than a general pre-reqs section, but for the rest of the guides going forward such as mpConfig/Kube and the mpHealth/Kube guide we talked about this can definitely be a shared section.

**Comment by yeekangc** [comment]
Yes, https://github.com/OpenLiberty/guides-common is an option.  Please work with @gkwan-ibm and @evelinec and see what is best.

**Comment by proubatsis** [comment]
PR Merged
