### ISSUE TITLE
ID review comments for Guide for Kube + MP Config

### ISSUE THREAD

**Issue by helyarp** [OpenLiberty/draft-guide-kubernetes-microprofile-config#12]
Reviewed https://github.com/OpenLiberty/draft-guide-kubernetes-microprofile-config README.adoc

My overall impression is that the guide is well written and looks easy to follow. If I have time tomorrow (10/11/18), I'll try the steps on a Kubernetes installation. For expediency, should I add the **ID complete** label (`#f78678`) now?

My comments are suggestions, unless marked **required**.

**What you’ll learn**
- [x] Replace "since" with "because" in "Externalized configuration is useful since configuration..." 
- [x] Consider replacing "using"/"by using" with "with" sometimes (global)
- [x] "You will also learn how to configure the environment by providing required values to your application using Kubernetes, this allows for easier deployment to different environments." is two sentences. Make the comma a semi-colon (;) or maybe remove "this allows"
- [x] The "it" in "By using MicroProfile Config to handle your configuration, it provides useful annotations that you may use to inject configured values into your code." is somewhat confusing. Maybe shorten the sentence to: "MicroProfile Config provides useful annotations that you can use to inject configured values into your code."
- [x] Shorten "If you want to learn more about MicroProfile Config read the Configuring microservices guide." to: "To learn more about MicroProfile Config, read the Configuring microservices guide."
- Maybe use "you'll" more often, instead of "you will" (global)
- [x] **required**: Change the "that" to "and" in "These resources are provided by Kubernetes **that** act as a data source for your environment variables."
- [x] Shorten "By creating a ConfigMap or Secret, they can be used to set environment variables for any number of containers as you see fit." to "You can use a ConfigMap or Secret to set environment variables for any number of containers."

**Prerequisites**
- [x] Under **Windows | Mac**, change "You will use the Docker Desktop" to "Use the Docker Desktop". Also, "If you do not see the Kubernetes tab then you have an older version of Docker Desktop, upgrade to the latest version." is two sentences. Maybe change comma to a semi-colon (;) or add "and must".
- [x] **required**: Change "Setup" to "Set up" in "Setup Docker for Windows/Mac as described in..."

**Starting and preparing your cluster for deployment**
- [x] **required:** Use "**K**ubernetes" instead of "kubernetes" in "a healthy **k**ubernetes environment..." Kubernetes is a registered trademark: https://www.linuxfoundation.org/trademark-usage/
- [ ] In Linux, do they have to log on as root user? Also, after they clone, is there a specific directory from which they need to run commands? If so, maybe clarify the user and directory for the command line. (global)
- [x] Change "By running this command, you will be able to interact" to "After running this command, you'll be able to interact"

**Deploy the name and ping applications**
- [x] Change "There are two applications that you will deploy —` name `and `ping`." to "You'll deploy two applications,` name `and `ping`." ( — is okay to use, instead of the comma)
- I like the period (.) before a command in "navigate to the `start` directory and run the following command." Other places in the guide use a colon, but the period looks cleaner.
- [x] Provide more info for the get pod status. Instead of "When they are ready the output will look similar to the following output." maybe use "When the pods are ready, the output shows `1/1` for READY and `Running` for STATUS." 
- [x] Change "Then navigate" to "After the pods are running, navigate..."
- [x] We typically use "IP address" instead of "ip address" (IBM Terminology guidelines say to use "IP" but the OL guides might follow a different standard. http://tlwi.w3-969.ibm.com/standards/terminology/cgi-bin/lookup?ug=corporate&term=ip&submit=Search&source=en&target_switch=none&template=simple&db_name=LOGOS&11=main+form&11=acronym%7Eabbreviation&11=prohibited)
- [x] Change "By default it" to "By default, it"
- [ ] Near the bottom of the **Deploy the name and ping applications** section, it might help to add a command that displays the cluster info (with IP address). I think the command is `kubectl cluster-info`

**Create ConfigMap and Secret**
- We normally use "enables" instead of "allows" unless permission is needed. (Allows denotes permission.) But I think "allows" is okay in the guide because it is more casual.
- [x] Shorten "individual key-value pairs that you want stored in this ConfigMap." to "individual key-value pairs to store in this ConfigMap."
- [x] Shorten "There are other options available such as --from-file and --from-env-file to allow for more versatility with respect to what you want to configure." to: "Other available options, such as `--from-file` and `--from-env-file`, provide more versatility as to what you want to configure."
- [x] Maybe change "More details about " to "Details about "
- [x] Use lowercase "d" in "in the "Kubernetes CLI **D**ocumentation." (a nit)
- [ ] Maybe change ", in other words" to ", or" (a nit)
- [x] **required**: Remove the "a" from "and **a** secrets to store public/private key pairs."
- [x] Change "A Secret is similar to a ConfigMap, the main difference is that a Secret" to "A Secret is similar to a ConfigMap, except a Secret"
- [x] Clarify the "They" in "They don’t provide any encryption by default," (Secrets?)

**Update Kubernetes resources**
- [x] Remove "Update the kubernetes resources in the `kubernetes.yaml` file:" (The previous sentence provides the needed info.)
- [ ] Shorten "These sources include a ConfigMap, a Secret, and information about the cluster." to "These sources include a ConfigMap, a Secret, and the cluster."
- [x] Change "In this example configMapKeyRef is used to get the value message from the ConfigMap greeting-config. Similarly, secretKeyRef is used to get the values username and password from the Secret name-credentials." to "In this example, `configMapKeyRef` **gets** the value `message` from the ConfigMap `greeting-config`. Similarly, `secretKeyRef` **gets** the values `username` and `password` from the Secret `name-credentials`."

**Deploy your changes**
- [x] Change "is working as intended, if it is not then you may have misconfigured the credentials." to "is working as intended. If it is not, then check the configuration of the credentials." (separate into two sentences)

**Testing the microservices**
- [x] The "appropriately" isn't needed in "and **appropriately** substituting `[hostname]`"
- [x] Change "Once" to "After" in "Once the tests succeed"

**Tearing down the Kubernetes resources**
- [x] Change the sentence to "Run the following commands to delete all the resources that you created."

**Comment by proubatsis** [comment]
These PRs cover the required feedback

#13 
https://github.com/OpenLiberty/guides-common/pull/187

Please review @helyarp @evelinec

**Comment by evelinec** [comment]
Checked with @helyarp who's ok with the remaining unchecked points above. 

I can see these 2 points could be better usability. @proubatsis would you consider them?

- [ ] In Linux, do they have to log on as root user? Also, after they clone, is there a specific directory from which they need to run commands? If so, maybe clarify the user and directory for the command line. (global)

- [ ] Near the bottom of the Deploy the name and ping applications section, it might help to add a command that displays the cluster info (with IP address). I think the command is kubectl cluster-info

**Comment by proubatsis** [comment]
@evelinec 

> In Linux, do they have to log on as root user? Also, after they clone, is there a specific directory from which they need to run commands? If so, maybe clarify the user and directory for the command line. (global)


They do not need to be logged in as root. The only part they'll need root for is the set up process in the separate doc I wrote (currently in the wiki of the kube intro guide).


> Near the bottom of the Deploy the name and ping applications section, it might help to add a command that displays the cluster info (with IP address). I think the command is kubectl cluster-info


I gave this some heavy consideration, but I came to the conclusion that it is probably more clear in its current state. The `cluster-info` command won't necessarily be accurate in all situations, we'd have to give platform specific instructions for this to work. Something along the lines of "Docker Desktop is always localhost" and for minikube "run the `minikube ip` command".

Maybe it would work if we change up the existing paragraph, and instead of talking about the defaults we just tell them "this is the exact information you need". I'll make this change to show you what I mean.

**Comment by evelinec** [comment]
@proubatsis thanks for addressing the remaining points. 

Regarding ```In Linux, do they have to log on as root user? Also, after they clone, is there a specific directory from which they need to run commands? If so, maybe clarify the user and directory for the command line. (global)```
perhaps to clarify which directory user  is to work with?

**Comment by evelinec** [comment]
Ok, not a problem. Thanks.
