### ISSUE TITLE
Pre test on Mac

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-kubernetes-microprofile-config#16]
General

- [x] Some section headings do not start with a gerund. 

- [ ] About updating a class or yaml file, in general, it's more user error prompt. It takes a while to figure out what exactly is the differences in the listed file and those lines that need to be updated in the `start` folder files.

Create ConfigMap and Secret

- [x] It has a key called meeting with a value of Greetings…​. => a key called "meeting"? 

- [ ] This link to "Kubernetes CLI documentation" doesn't show up accurately to the "configmap" section of the doc. But the link is accurate. Not sure this is fixable. Problem happens with Firefox, Chrome works fine. 

- [x] it only shows you a Base64 encoded version so that a casual onlooker doesn’t accidentally see any sensitive data => should "Base64" be back ticked? 

Related guides

- [x] Not sure about this guide is related to the docker and istio guides. Perhaps the "MicroProfile Config", "CDI-Intro" and "Kube-Intro" guides? 

Tags

- [x] mpConfig => should be "Config" or "MicroProfile Config"?

**Comment by yeekangc** [comment]
MP Config and Kube Intro as related guides are fine.  Shouldn't need to link it to CDI.

These comments don't feel like pre-publishing test's comments to me.  Looks like we aren't ready for publishing.

**Comment by yeekangc** [comment]
Base64 shouldn't need to be in quotes since it is a commonly known term.

**Comment by evelinec** [comment]
This guide does use CDI inject annotation, thus I thought that it can be related to the CDI-Intro guide.

**Comment by evelinec** [comment]
Fair enough the "Base64", I was double thinking about that too.

**Comment by yeekangc** [comment]
The key for Related Guides will be what is most relevant.  Otherwise, we can be linking to everything.  =)

**Comment by evelinec** [comment]
The issues I raised are addressed and verified in #19.
