### ISSUE TITLE
Gilbert's comment

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-kubernetes-microprofile-config#3]
- [x] Should the guide title  be "Configuring microservices with Kubernetes"?
- [x] The  Prereq section tells "...you should have a Kubernetes cluster available ...". In case users not start docker and cluster yet, (or not even learn the Intro guide), make sure users have run the instructions in the "Starting and preparing your cluster for deployment" section of the Kube Intro guide
- [x] is it possible to highlight the text to be updated for NameResource.java, PingResource.java and kubernetes.yaml?
- [x] add license text to web.xml
- [x] following import not necessary in NameEndpointTest and PingEndpointTest
```import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.security.cert.X509Certificate;
import java.security.cert.X509Certificate;```

**Comment by proubatsis** [comment]
PR Merged
