### ISSUE TITLE
Review comments from Navid

### ISSUE THREAD

**Issue by navidsh** [OpenLiberty/draft-guide-kubernetes-microprofile-config#7]
- [x] The title is a little bit misleading. We are trying to configure microservices running in a Kubernetes environment. How about "Configuring microservices running in Kubernetes"?
- [x] "When this command finishes, wait for the pods to be in the Ready state...": Are we assuming users would know how to check the pod's states? Should we provide the command to check the pod's state?
- [x] "These sources include a ConfigMap, a Secret, information about the cluster, and the pod’s required resources.": What are you referring to by "the pod’s required resources."?
- [ ] ~Did you try using `kubectl patch -f kubernetes.yaml` instead of `kubectl delete -f kubernetes.yaml kubectl apply -f kubernetes.yaml`?~

**Comment by proubatsis** [comment]
#9

**Comment by proubatsis** [comment]
PR Merged. Thank you 👍
