### ISSUE TITLE
Tommy's Review

### ISSUE THREAD

**Issue by wojtczat** [OpenLiberty/draft-guide-kubernetes-microprofile-config#8]
I honestly did not find many faults in this guide. I enjoyed the detail with which ConfigMaps and Secrets were presented. Every instruction was nicely broken down allowing the concept to be easily understood. My one issue probably falls more on the design team as I found it somewhat annoying to read through my .java and .yaml files to find what I needed to add or change when following the interactive steps. These files were relatively small so it did not hurt my experience too much, but in larger files this could be a much larger issue. If there is a way to highlight the specific text that the user is supposed to include in the file they are to edit, that would definitely increase the ease of use.

**Comment by proubatsis** [comment]
As I understand it this will be addressed with the new multi-pane design. Can you confirm @evelinec ?

**Comment by yeekangc** [comment]
Yes, this should be addressed by the multi-pane design.

The approach in general at the moment is to show the whole file to make the experience working with the guides simpler i.e. copy and pasting to avoid unnecessary mistakes.

@evelinec @gkwan-ibm

**Comment by yeekangc** [comment]
I think I finally understand the issue now.  These need to be addressed.

**Comment by yeekangc** [comment]
Addressed in #19.  @wojtczat, feel free to take a look at the latest and re-test.
